### ISSUE TITLE
Re-think design of the WIP article conversion pop-up

### ISSUE THREAD

**Issue by lentschi** [foodcoopsat/foodsoft_hackathon#15]
![grafik](https://user-images.githubusercontent.com/783944/202863814-21ff249e-a7b7-40b2-b8d4-18d85f2a438d.png)

siehe https://forum.foodcoops.at/t/foodsoft-artikeleinheiten-hackerton-start-fixieren/5951/78

**Comment by lentschi** [comment]
I'll try and make a proposal for this.

**Comment by twothreenine** [comment]
I think the button to open the popup is a good solution :+1:
Just with the order of the buttons/input I'm not sure, but that's a different topic. (perhaps `-` `+` `input` `convert` ?)

On mobile, the popup looks broken:
[Chrome]
![20240421_105705](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/60bea462-18d8-4374-bbab-f7f9d7bd58f9)

[Firefox]
![20240421_105723](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/14a72f34-31be-4484-9fd2-e246538b87d4)

Also, the popup would be easier to use on mobile if there were large -/+ buttons next to the amount input inside the popup, like the ones in the table.

**Comment by lentschi** [comment]
> Just with the order of the buttons/input I'm not sure, but that's a different topic. (perhaps - + input convert ?)

Yeah, if you'd agree with that suggestion, @yksflip, I'd actually change it to that sequence.

**Comment by lentschi** [comment]
Closing it for now - design seems okay
