### ISSUE TITLE
Remove temporary db seeds used by this fork ("hackathon") and fix the existing seeds for the new db structure

### ISSUE THREAD

**Issue by lentschi** [foodcoopsat/foodsoft_hackathon#16]
- [x] Adapt seeds to match new db structure (see samples in current hackathon files)
- [x] Add `article_units` to each seed file (also see samples in current hackathon files)
- [x] Remove hackathon seed files.

**Comment by yksflip** [comment]
i could work on this ...
Maybe we can rename the hackathon_de.seeds.rb as `small.de.seeds.rb` and keep it as a german seed?
