### ISSUE TITLE
"Automagische" Migration von Artikeleinheiten

### ISSUE THREAD

**Issue by lentschi** [foodcoopsat/foodsoft_hackathon#18]
Einheiten aus den Ausgangs-DBs wie diese...:

```
unit = 100g
unit_quantity = 10
```

...können (durch Regex-Erkennung) automatisch umgewandelt werden in Daten wie diese:

```
supplier_order_unit = KGM
group_order_granularity=100
group_order_unit=GRM
```

**Comment by twothreenine** [comment]
> Einheiten aus den Ausgangs-DBs wie diese...:
> 
> ```
> unit = 100g
> unit_quantity = 10
> ```
> 
> ...können (durch Regex-Erkennung) automatisch umgewandelt werden in Daten wie diese:
> 
> ```
> supplier_order_unit = KGM
> group_order_granularity=100
> group_order_unit=GRM
> ```

Bei diesem konkreten Beispiel sehe ich das Problem, dass bei supplier_order_unit = KGM ja nicht nur Gesamtmengen in ganzen kg abgeschickt werden können sollen, sondern auch z.B. 2,8 kg (je nach group_order_granularity).
10x100g heißt hingegen, dass insgesamt nur Gebinde à 1 kg (bzw. 10 Stück à 100 g) bestellt werden können.
Die Umwandlung müsste also lauten:

supplier_order_unit = Gebinde/pack (weiß nicht, was da die beste UN/ECE Einheit ist)
und dann entweder mit ratios: pack contains 10 x package, package contains 100 g, group_order_unit = package
oder alternativ: pack contains 1000 g, group_order_unit = GRM, group_order_granularity = 100

Hast du das bei der Umsetzung beachtet? @lentschi

**Comment by lentschi** [comment]
@twothreenine Funktioniert bereits wie in "alternativ" vorgeschlagen
