### ISSUE TITLE
New page: Units administration

### ISSUE THREAD

**Issue by lentschi** [foodcoopsat/foodsoft_hackathon#24]
Location in menu: At the bottom in "Articles"
Menu point label: "Units"
Required Permission: `role_article_meta`

- Displays currently selected units (for the current instance's locale) which will be eligible in the article forms' dropdowns
- Allows adding UNECE units:
  * Units can be added by a typeahead that allows selected from all existing UNECE units
  * Checkbox "Only select from recommended units" (default: checked) will limit the available units to those that have been translated (see #10)
  * Each unit may only be added once
  * Adding units that do not have a translation will display a warning like "No unit translation available. If you really want to use this unit and believe other foodcoops might want to too, please create a GitHub issue [here]"
- Allows removing selected units:
  * Using a delete button provided in each row
  * Prevents deletion of units if they are currently used in the most recent article versions

Required DB migration:
- Add `available_units` table with one unique field: `unit`.
- (? possible ?) Add certain defaults based on the foodcoop instance's timezone. E.g. metric units for Europe

**Comment by twothreenine** [comment]
> Checkbox "Only select from recommended units" (default: checked) will limit the available units to those that have been translated (see https://github.com/foodcoopsat/foodsoft_hackathon/issues/10)

This feature is missing,
Another option would be to rank the translated units above the others, so when you search for `kg` or `kilo`, you get `kilogram` among the first results instead of a long list of non-useful units first.
