### ISSUE TITLE
Leerzeichen zwischen Zahl und Einheit?

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#33]
Ich denke, da sollte ein Leerzeichen gesetzt werden, also `500 g` statt `500g` und `1.3 kg` statt `1.3kg`.
Es macht Einheiten besser lesbar und ist Standard, jedenfalls im Deutschen und Englischen:

Austrian Standards, [Der korrekte Umgang mit Größen, Einheiten und Gleichungen](http://cdn.austrian-standards.at/asset/dokumente/produkte-loesungen/kostenlose-services/fachinformationen/23-groessen/FI23_Einheiten.pdf):
> Der Zahlenwert steht immer vor der Einheit. Zwischen der Zahl und der Einheit ist immer ein Leerzeichen einzufügen. Diese Regel gilt auch für Prozent (%), Promille (‰) und Grad Celsius (°C). Die einzigen Ausnahmen zu dieser Regel sind die Einheitenzeichen für den Grad, die Minute, die Neuminute, die Sekunde und die Neusekunde des ebenen Winkels, die den Zahlen ohne Leerzeichen nachgestellt werden. Es ist darauf zu achten, dass zwischen Zahl und Einheit kein Zeilenumbruch erfolgt."

[Wikipedia-Richtlinie zur Schreibweise von Zahlen](https://de.wikipedia.org/wiki/Wikipedia:Schreibweise_von_Zahlen):
> Zwischen eine Zahl und die zugehörige Maßeinheit gehört immer ein Leerraum – ausgenommen Maßeinheiten, die ausschließlich aus einem einzelnen hochgestellten Zeichen bestehen, wie etwa ° ′ ″ für Grad, [Fuß](https://de.wikipedia.org/wiki/Fu%C3%9F_(Einheit)), [Bogensekunde](https://de.wikipedia.org/wiki/Winkelsekunde) und so weiter. Ist die Maßeinheit abgekürzt, kann ein [geschütztes Leerzeichen](https://de.wikipedia.org/wiki/Gesch%C3%BCtztes_Leerzeichen) (etwa `&nbsp;` in HTML) gesetzt werden, um einen unschönen Zeilenumbruch zwischen Zahl und Maßeinheit zu vermeiden.

[international standard](https://en.wikipedia.org/wiki/International_Organization_for_Standardization) [ISO 31](https://en.wikipedia.org/wiki/ISO_31) on [quantities](https://en.wikipedia.org/wiki/Physical_quantity) and [units](https://en.wikipedia.org/wiki/Physical_unit) - inzwischen abgelöst von ISO 80000, darin finde ich aber nichts zu dem Thema, daher gehe ich davon aus, dass es gleich geblieben ist:
> Numerical value and unit symbol are separated by a space. This rule also applies to the symbol "°C" for degrees Celsius, as in "25 °C", and to the [percent sign](https://en.wikipedia.org/wiki/Percent_sign), as in "10 %". The only exceptions are the symbols for the units of plane angle: degree, minute of arc, and second of arc – which follow the numerical value without a space in between (for example "30°").

Ich denke, die Ausnahmen für ° etc. können wir uns sparen, da die Verwendung einer solchen Einheit recht unwahrscheinlich ist.
Ein geschütztes Leerzeichen wäre am besten.

**Comment by lentschi** [comment]
@twothreenine Danke für deine Recherche - werde ich so umsetzen!
