### ISSUE TITLE
Order menu: Some articles remain marked yellow after reaching minimum order quantity

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#39]
It occured at Foodsoft one / Hackathon / oyster mushrooms: The minimum order quantity is 1.2 kg. When I type in 1 [kg] the row gets marked red (correct) but when I enter 1.2 or anything above, it gets marked yellow, It should be green though.

It works for Bread rolls, though: At 4 [pieces] it gets marked yellow (only 1 missing), at 5 it gets marked green. Also when I enter 20 directly instead of using the + button.

**Comment by lentschi** [comment]
Had the same cause as #48 and is thus fixed by https://github.com/foodcoopsat/foodsoft_hackathon/commit/9642e9b4f8b53f5559c2a532cd4612354850bb70
