### ISSUE TITLE
Missing error message when entering invalid amount in the order menu, esp. on mobile

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#40]
I used the conversion popup to order 2 kg of bread rolls (350 g a piece) which brings me to the amount of 5.7143 pieces. As bread rolls can only be ordered in whole pieces, this is an invalid amount to order. The field is marked red while the cursor is inside, but I can click outside and don't get any further hint.
Only when I click `save order`, I get an error message:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/fa053bfd-d4d3-4e93-a42d-6b486f990337)
It would be more user friendly if this message was shown directly after clicking `Apply`.

**I tried this on my phone as well, there I don't see this message at all after clicking `Save order`. I just can't save the order without any hint of what is wrong.**

**Comment by lentschi** [comment]
> I tried this on my phone as well, there I don't see this message at all after clicking Save order. I just can't save the order without any hint of what is wrong.

Which mobile browser are you using? It didn't happen for me with Vanadium (webkit-based).

**Comment by twothreenine** [comment]
It happens to me in Firefox.
Just checked, in Chrome the error message is shown.

**Comment by lentschi** [comment]
Ah -Firefox mobile has veeeery little market share. Though I'm all for supporting it, to fight webkit's monopoly, I'm not sure we should use it for preliminary testing. (Btw. - on a completely different matter - the problem with the group order save button being covered by the footer also seems to arise only on firefox mobile; I guess that's why no one has addressed it so far and I personally think we shouldn't invest too much time in it now. When shifting to a modern ui we should keep firefox mobile in mind though.)

In any case, you said, you were even able to _save_ the group order. That's not good. I might have forgotten to implement backend validation of granularity. I'll look into it!

**Comment by twothreenine** [comment]
> Firefox mobile has veeeery little market share [,..] I'm not sure we should use it for preliminary testing.

Ah, didn't know that, it's my default browser since I have all my bookmarks and passwords in Firefox. According to statcounter.com, its current market share is 1.35 % in Austria, 1.75 % in Germany. I'm not sure if we should ignore that.

> the problem with the group order save button being covered by the footer also seems to arise only on firefox mobile; I guess that's why no one has addressed it so far 

Yeah, I noticed that it is better in Chrome, however in some cases the save button disappears as well.
Also, there _have been_ other people who addressed this issue.

> In any case, you said, you were even able to save the group order. That's not good. I might have forgotten to implement backend validation of granularity. I'll look into it!

I wasn't able to save it, I was only able to click on the save button, but nothing happened.

**Comment by lentschi** [comment]
> According to statcounter.com, its current market share is 1.35 % in Austria, 1.75 % in Germany. I'm not sure if we should ignore that.

I'm not saying we should ignore that. However, in this ancient frontend stack we're on right now, cross-browser optimizations/bugfixes are unnecessarily difficult to implement. So I'd say, let's only fix what's absolutely necessary as it will only affect < 2% of mobile users.

> I wasn't able to save it, I was only able to click on the save button, but nothing happened.

I see, that looks like a firefox mobile bug to me then.

**Comment by twothreenine** [comment]
> I see, that looks like a firefox mobile bug to me then.

The problem is that Firefox doesn't jump to the erroneous field and doesn't show the error message.

**Comment by lentschi** [comment]
Yes, and I believe that's a firefox _mobile_ bug then (maybe this one, but I didn't read into it: https://bugzilla.mozilla.org/show_bug.cgi?id=1510450).
Firefox _on desktop_ handles the invalid field logic fine though.
