### ISSUE TITLE
Received amounts should be displayed in billing unit

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#44]
Smoked tofu has hectogram as billing unit.
The accounting menu looks like this:

![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/0edad515-307b-466a-bf17-f497d26373f2)

Shouldn't the "received" amounts be `3.2` and `1.6` ?

Let's say Anton received only 295 g instead of 320 g. I can enter this via the conversion popup (a bit cumbersome esp. if you need to change the amount for many ordergroups) and calculate a received amount of `1.844` packages:

![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/3720e3f4-c8ac-4aa2-a33a-1e0418bd7c5a)

Then there's a red exclamation mark because the group amount sum doesn't match the total amount of 4.8 hg. I need to alter the total received amount, but to find it out I have to use a calculator to calculate `2.844 * 160 =~ 455` -> now I know that I have to change it to 4.55 hg.
It would be much easier if both the group order amounts would be displayed directly in the billing unit (with the option to change the amount) as well as the sum of the group amounts.

**Comment by twothreenine** [comment]
I think this should apply to all menus/cases where received units appear:

- [x] manage order menu: sorted in articles / sorted in groups
- [x] article sorted PDF -> foodcoops/foodsoft#1099 
- [x] group sorted PDF
- [x] group order result (of a closed or settled order)
- [x] receive menu (can be improved?)
- [x] accounting menu: group order amounts (see posting above)
- [ ] accounting menu: edit article modal (currently, both ordered and received amounts are displayed in the billing unit here)

For better understandability, I'd suggest to always include the respective units, like in the receive menu:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/eadb824a-cea4-462a-83fd-42892c8fa256)
Further suggestions:
- [ ] Always show the order & billing units (inluding for beer, carrots and oyster mushrooms)
- [ ] [receive menu] rename the title of the _Unit_ column to or _Unit (ordered per)_

**Comment by lentschi** [comment]
@twothreenine I'm not sure, I understand this sub task:
> accounting menu: edit article modal (currently, both ordered and received amounts are displayed in the billing unit here)

For an arbitrary example where we have hectogram as `supplier_order_unit`, gram as the `group_order_unit` and kilogram as the `billing_unit`, we'd currently see the following at the top of the dialog you're addressing:

![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/783944/dfd713b0-ac34-416d-9233-2d77e6a76926)

And now you're saying, we should see gram for the "Ordered units"...? Wouldn't that be kind of hard to compare then...? (Personally, I'd stick with billing unit for both here.)

**Comment by twothreenine** [comment]
> And now you're saying, we should see gram for the "Ordered units"...? Wouldn't that be kind of hard to compare then...? (Personally, I'd stick with billing unit for both here.)

I see your point. However, in that case, you could still use the conversion popup for comparing.
Yes, I'd stick with the `group_order_unit`. "We ordered 3 packages, we got 4.74 hg" like in all other menus. That would make it easier to compare e.g. to amounts on an article-sorted PDF and I think it would avoid confusion.
But I'm not sure. You could also say it should be `supplier_order_unit` ...

No matter what, I think those should be unit symbols and without x if scalar (like in the receive menu).

**Comment by twothreenine** [comment]
> accounting menu: group order amounts 

To make it clearer to which unit the group order amounts refer, I'd suggest adding the unit symbol after the input fields.
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/0fc78307-49f6-4ade-9ded-78d2a69514cc)

Same for the manage order menu -- esp. in article sorting, the unit is only displayed very small on the right and easy to overlook when editing the amounts on the right, esp. on a wide screen:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/c7afa59b-ae41-49a3-8498-2567afde5726)

**Comment by lentschi** [comment]
This issue's discussion has deviated a bit from the original description. I think the main points have been implemented (except for [the one that is still unclear](https://github.com/foodcoopsat/foodsoft_hackathon/issues/44#issuecomment-1925872474).)

I'm closing this for now. 

- If I've still missed occurrences of units that should certainly be displayed in billing unit, but aren't, please comment & reopen.
- If there are other issues (design etc.) or if the remaining unclear point has been clarified, please create separate issues, thank you! :slightly_smiling_face:
