### ISSUE TITLE
Improve understandability of article form (labels, locales, tooltips)

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#50]
I've seen you've changed `supplier order unit` to `delivery unit`. Generally I'm not really happy with the texts at the moment, "Can be ordered per" does not specify whether _from the supplier_ or _by ordergroups_. I think this should be clearer. My suggestions:

![Hackathon article form EN drawio](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/4284daa1-2466-4433-875d-12c08710421f)

`internally orderable per` is of course meant as an alternative suggestion, I prefer the one above though.
edit: `members can order per` isn't too long either

![Hackathon article form DE drawio](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/2d712cff-3eed-416d-95f0-a9687d739604)

`Einheiten-Umrechnungen` sounds very confusing to me. `Inhalt` would be a loose translation, but clearer, I guess. You could even use "content" in English. I think this would describe the main use case here best. Adding a ratio like ml/g will be the exception. I think we should explain how ratios can be used in a tooltip.

**Comment by lentschi** [comment]
@twothreenine Those are just initial ideas (just so we can test the multi language setup on the demo server).
I'm not sure, it makes sense to discuss each single translation here.

I suggest we finish everything in English first and then discuss translations directly in the translation files (e.g. via PR). Would that be okay for you? (If so, I'd close this issue - after all there's foodcoops/foodsoft#1101 to tackle this)

**Comment by twothreenine** [comment]
I just wanted to note this for later as I thought about it.
I think it does make sense to discuss the labels of this menu together, and the tooltip thing isn't tackled by foodcoops/foodsoft#1101.

After the current issues are solved, I'd suggest we complete the translations to German and then invite ppl from the Austrian forum for a wider test, both for understandability as for bugfinding.

**Comment by lentschi** [comment]
Okay, but please create a separate issue to discuss adding tooltips etc. I'm closing this issue now to avoid confusion.
