### ISSUE TITLE
Order menu: Color highlighting / missing amount don't work properly in some cases

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#52]
I'd expect the following behavior: (= current behavior on upstream)
- When `missing > 1`, the row is highlighted red
- When `0 < missing <= 1`, the row is highlighted yellow
- When `missing = 0` and `group order amount > 0`, the row is highlighted green
- When `missing = 0` and `group order amount = 0`, the row is not highlighted

Alternatively, you could also expect: (my suggestion)
- When `group order amount = 0`, the row is not highlighted
- When `group order amount > 0`
  - and `missing > 1`, the row is highlighted red
  - and `0 < missing <= 1`, the row is highlighted yellow
  - and `missing = 0`, the row is highlighted green

Behavior in FS one:

Bread:
- In a new group order, when I click on `+` once (so that 0.5 is missing) it stays without highlighting, but should turn yellow.
- When editing the group order with 0.5 bread saved, it's highlighted red. When I then increase the amount to 1, it stays red instead of turning green, although missing = 0. (Same when I order an additional 0.5 as a different ordergroup, so that the total amount is 1)

Bread rolls:
- When I decrease the amount to 0, the row stays red instead of blank

Beer:
- When I decrease the amount to 0, the row is highlighted green instead of blank

Oyster mushrooms:
- When I save an order of total 0.7 kg (so 0.5 kg missing) and then edit it, it's displayed as missing = 0, not highlighted, with amount `0.7 + 0` (should be `0 + 0.7`). When I then increase it to 0.8, missing is 0.4 and it's highlighted red, but the amount says `0.7 + 0.1` (should be `0 + 0.8`)

**Comment by lentschi** [comment]
@twothreenine It's true, there were some bugs in that, which I now fixed.
However a small deviation from your suggestion: I use `group_order_granularity` instead of the hardcoded value of `1` as a threshold to determine, whether the background turns red or yellow. (After all the +/- buttons also use that.)

**Comment by twothreenine** [comment]
> I use group_order_granularity instead of the hardcoded value of 1 as a threshold to determine, whether the background turns red or yellow. (After all the +/- buttons also use that.)

Hmm, so if the external order unit is 25 kg and the internal one is 0.001 kg, then it turns yellow only at 24.999 ?

However, if the external order unit is package (0.75 kg) and the internal order unit is 0.05 kg, then it would make more sense to let it turn yellow at 0.70 kg than having it always yellow. 🤔
