### ISSUE TITLE
Some numbers not localized (decimal point/comma)

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#60]
In German, these numbers should be with decimal comma instead of decimal point:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/275332cf-0791-4771-9d0a-058213c5f433)

The unit content (in brackets) also affects the order placement menu.
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/6b574adc-3cbf-44c3-81a7-6142b5cf87d6)

**Comment by lentschi** [comment]
> In German, these numbers should be with decimal comma instead of decimal point

That seems to be a firefox bug:
https://stackblitz.com/edit/stackblitz-starters-wq7ukz?file=index.html

```html
<input type="number" value="1.0">
<input type="number" value="1.3">
```

<- In Chrome (v123.0.6312.105 with the preferred content language set to German) both those inputs look like this: 
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/783944/bf13543b-9c29-4ee4-80d3-e4361310907d)

In firefox (124.0.2) the first input (the one with a value of `"1.0"`) uses a dot as a decimal separator for some inexplicable reason:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/783944/b404bac4-dbc6-47cc-82a9-409d8b7d8750)

I couldn't find that precise bug on bugzilla, but to me it seems to _be_ a bug. (Or at least I don't get why those two inputs should behave differently.)

One could work-around this by fixing the associated rails issue: Not passing zero insignificant zeroes to decimal inputs, but that would be quite some effort as we'd have to either wrap the simple form input logic, or manually custom format the value in each occurrence in the templates, so I'm closing this for now.

> The unit content (in brackets) also affects the order placement menu.

That part is fixed. :+1:
