### ISSUE TITLE
Prevent +/- buttons from jumping left and right in order placement menu

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#61]
This is really annoying when you use the +/- buttons and you can't click on them continuously because they jump left and right.
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/8881c5df-5ca4-4917-bbdd-df3970cf8a9e)

Idea: Seperate columns for amount preview and input? Same for tolerance preview and input? All aligned left, and preview should have a large enough minimum width to allow for `0.123 + 0.456`

btw _**if**_ the column content is center-aligned, the column headings (amount, tolerance) should be center-aligned as well.

**Comment by lentschi** [comment]
That behavior is also happening with the current upstream version of foodsoft and has nothing to do with the changes.
However introducing decimal values escalates the issue somewhat. (Before the layout only "jumped" when reaching numbers > 10)
