### ISSUE TITLE
Amount input field too small in various menus

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#67]
I think these input fields should be big enough to display amounts like `12.345`:

Order management (group/article sorting):
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/4e2a26cd-bc9e-4aeb-bf94-c3d30b2f1d77)

Receive menu:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/24526497-144d-4798-bfef-637d6e907e6c)

Accounting:
![grafik](https://github.com/foodcoopsat/foodsoft_hackathon/assets/22921479/d86d31cc-efab-4206-903e-4ce7fe2f0937)

**Comment by lentschi** [comment]
It's been made smaller by [my change](https://github.com/foodcoopsat/foodsoft_hackathon/commit/7577e815319bb3595655d9f2f24efa32d1404d91) to have a button (instead of input focus) trigger the conversion popover. But that change was just a suggestion that hasn't been approved yet, so I'm waiting for feedback on that before I fine tune things like this.

**Comment by lentschi** [comment]
> But that change was just a suggestion that hasn't been approved yet, so I'm waiting for feedback on that before I fine tune things like this.

So, to address you directly @twothreenine , @yksflip : Do you prefer the open-by-button approach (as in the current version - but without formatting errors as described in this ticket) or should I roll back to the open-on-focus approach?
Advantage of the current approach (which I personally prefer): 

- Opens only when requested
- Better keyboard navigation (TAB-key)
- Less annoying on mobile devices (once properly implemented) as the conversion popover covers a lot of the screen when opened

Advantages of the previous approach:

- More space for the input itself (no space used up by the conversion button)
- Saves the extra click / key press

**Comment by twothreenine** [comment]
> So, to address you directly @twothreenine , @yksflip : Do you prefer the open-by-button approach (as in the current version - but without formatting errors as described in this ticket) or should I roll back to the open-on-focus approach?

I responded to that in the other issue: https://github.com/foodcoopsat/foodsoft_hackathon/issues/15#issuecomment-2067974018
I prefer the open-by-button approach and think that the advantages you pointed out clearly outweigh its disadvantages for the majority of the use cases.

**Comment by lentschi** [comment]
Ah, great! :)

**Comment by yksflip** [comment]
agree, I'd also prefer the button approach

**Comment by twothreenine** [comment]
How do you think the buttons should be arranged @yksflip ?
Currently, it's `+` `input` `convert` `-`.
My suggestion would be `-` `+` `input` `convert` (-+ together for quick corrections and in a more logical order, which we've talked about once, but we both forgot our conclusion).
lentschi said, this would also make solving this issue easier than with the convert button in between.

**Comment by yksflip** [comment]
I don't have a strong opinion about that. If you have user-feedback about what's most intuitive / the easiest way to use, I'd go for that, otherwise what's the simplest to implement ;)
for me `-` `+` feels like the more logical order
