### ISSUE TITLE
Support decimal comma in article CSV numbers (upload)

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#81]
When I try to upload a CSV (user language set to German) with a minimum order quantity of `1,2` [kg], I get an error.

In upstream, prices with decimal comma are supported in CSV upload, so other columns should support this as well, I think. (I haven't tested the other new columns.)

For the ratios column: Might decimal commas lead to problems here?

I can't find where to change this. I tracked the process until https://github.com/foodcoopsat/foodsoft_hackathon/blob/5be0082171f026d289cb43368cc42756637660d0/app/controllers/articles_controller.rb#L264
but I don't know where `supplier_articles_path(@supplier)` leads. @lentschi

**Comment by lentschi** [comment]
> For the ratios column: Might decimal commas lead to problems here?

Yes, as now our separator between ratios is a colon (as I think we agreed upon in https://github.com/foodcoopsat/foodsoft_hackathon/issues/47 - too lazy to read through all of that though :sweat_smile:), we logically cannot use it as a decimal point too.
