### ISSUE TITLE
Edit all articles: Price and price unit displayed incorrectly

### ISSUE THREAD

**Issue by twothreenine** [foodcoopsat/foodsoft_hackathon#85]
It seems to me that in the price unit dropdown, the supplier order unit is selected instead of the price unit.
The price is also displayed as it is saved in the database (per supplier order unit).

Bread example:
![grafik](https://github.com/user-attachments/assets/7c392d0f-00e8-4d72-962e-5c87c131df3f)
should be `3.00` per `kilogram`

similar to #83

**Comment by lentschi** [comment]
@twothreenine Which form/view are you referring to?

It looks like the article master data form to me, but I can't reproduce the issue: When opening the edit form of 'Bread' with the hackathon seeds (which I had to temporarily restore using `git checkout e517eb232abc32a3ebe8f3af8e9a75ab3ae7cc7e~1 -- db/seeds/hackathon.seeds.rb` as they [have already been removed](https://github.com/foodcoopsat/foodsoft_hackathon/pull/76/files) from the `master` ), the following is being displayed:

![grafik](https://github.com/user-attachments/assets/2f9f830a-3016-419a-a8d2-34b7da1dcb41)

Changing and saving price and/or unit seems to work properly too. (Of course you could _change_ it to piece, but that wouldn't be a bug...?)

**Comment by lentschi** [comment]
Aaah - you were referring to the "edit all" table. (@twothreenine Please add this info to the description too, not just to the title - that can be easily overlooked.)
